name: riverpod_mutations_annotation
description: The annotations for riverpod_mutations_generator
version: 2.0.0-dev.5
repository: https://github.com/TekExplorer/riverpod_mutations_generator

resolution: workspace

environment:
  sdk: ^3.6.0-0

dependencies:
  meta: ^1.0.0
  riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0

dev_dependencies:
  riverpod_generator: ^3.0.0
  build_runner: any
  lints: ^6.0.0
  test: ^1.21.0