name: workspace
publish_to: none
description: A code generator for Riverpod Mutations. This covers the hole left in Riverpod today.
repository: https://github.com/TekExplorer/riverpod_mutations_generator

# resolution: workspace

workspace:
  - packages/riverpod_mutations_annotation
  - packages/riverpod_mutations_generator

environment:
  # sdk: ">=3.0.0 <4.0.0"
  sdk: ^3.8.0
