name: riverpod_mutations_generator
description: A code generator for Riverpod Mutations. This covers the hole left in Riverpod today.
version: 2.0.0-dev.1
repository: https://github.com/TekExplorer/riverpod_mutations_generator

environment:
  # sdk: ">=3.0.0 <4.0.0"
  sdk: ^3.6.0-0

# dependency_overrides: 
#   riverpod_mutations_annotation:
#     path: ../riverpod_mutations_annotation
  # custom_lint_core: 0.6.10

dependencies:
  riverpod_mutations_annotation: ^2.0.0-dev.0
  riverpod_annotation: ^2.6.0
  analyzer: ">=7.0.0 <8.0.0"
  build: ^2.4.0
  build_config: ^1.1.0
  collection: ^1.19.0
  # crypto: ^3.0.2
  meta: ^1.16.0
  # path: ^1.8.0
  source_gen: ^2.0.0 
  recase: ^4.1.0
  code_builder: ^4.10.0
  source_helper: ^1.3.5
  # riverpod_analyzer_utils: ^0.4.1

dev_dependencies:
  lints: ^5.1.1
  build_runner: ^2.4.15
  build_test: ^2.2.3
  build_verify: ^3.1.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  riverpod: ^2.6.1
  riverpod_generator: ^2.6.3
  test: ^1.21.0
