name: riverpod_mutations_generator
description: A code generator for Riverpod Mutations. This covers the hole left in Riverpod today.
version: 1.0.3
repository: https://github.com/TekExplorer/riverpod_mutations_generator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  riverpod_mutations_annotation: ^1.0.2
  riverpod_annotation: ^2.2.1
  analyzer: ">=3.0.0 <7.0.0"
  build: ^2.0.0
  build_config: ^1.0.0
  collection: ^1.15.0
  # crypto: ^3.0.2
  meta: ^1.7.0
  # path: ^1.8.0
  source_gen: ^1.2.0
  recase: ^4.1.0
  # riverpod_analyzer_utils: ^0.4.1

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.1.7
  build_test: ^2.2.1
  build_verify: ^3.0.0
  freezed: ^2.4.3
  freezed_annotation: ^2.4.1
  riverpod: ^2.4.4
  riverpod_generator: ^2.3.5
  test: ^1.21.0
