targets:
  $default:
    builders:
      riverpod_generator:
        options:
          provider_name_strip_pattern: Notifier$
      riverpod_mutations_generator:
        enabled: true
        options:
          with_pair: true
        generate_for:
          exclude:
            - test
            # - example
          include:
            - example/*
            - test/integration/*
            - test/integration/**/*
builders:
  riverpod_mutations_generator:
    target: ":riverpod_mutations_generator"
    import: "package:riverpod_mutations_generator/riverpod_mutations_generator.dart"
    builder_factories: ["riverpodMutationsBuilder"]
    build_extensions: {".dart": [".riverpod_mutations.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    required_inputs: ['riverpod']